### ISSUE TITLE
Able to include a BOM?

### ISSUE THREAD

**Issue by dwjp** [OpenSprinkler/OpenSprinkler-Hardware#1]
Is it possible to include a BOM with component manufacturer and part numbers (and ideally distributor, e.g. Digikey, part number) for V3? I can probably figure out most details from schematic, but it'd be great to have something concrete.

**Comment by adrian78666** [comment]
I second this request.

**Comment by giig1967g** [comment]
i would like it too

**Comment by laurentopia** [comment]
Have you folks figured out the BOM?

**Comment by rubengr** [comment]
Is not public the BOM?

**Comment by laurentopia** [comment]
here is the BOM so far, I gave up
https://docs.google.com/spreadsheets/d/11xkz92zQxZZgTctV5IspjD9BH1N4TvmNcIJ9ATqKawM/edit?usp=sharing

**Comment by Egyras** [comment]
who can share AC ver. gerber file ?

**Comment by Egyras** [comment]
> here is the BOM so far, I gave up
> https://docs.google.com/spreadsheets/d/11xkz92zQxZZgTctV5IspjD9BH1N4TvmNcIJ9ATqKawM/edit?usp=sharing

Hi, who has AC ver. BOM file ?

**Comment by rayshobby** [comment]
1) We use a Chinese factory to manufacture the boards and they source the parts for us locally from China. So we don't have parts numbers in Digikey or Mouser because they don't buy parts from them.
2) The schematic has part values. Almost all parts are very common resistors, capacitors, diodes, transistors. A few ICs are not as common (like XL2001 switching regulator), but those parts are also clearly defined in the schematic.
