### ISSUE TITLE
Schematics in PDF?

### ISSUE THREAD

**Issue by ilium007** [OpenSprinkler/OpenSprinkler-Hardware#6]
Hi - I don't have or use Eagle. Would it be possible to see the schematics in PDF format? Cheers.

**Comment by ilium007** [comment]
Came here looking for PDF's schematics again and realised I already raised an issue for them! Any chance of PDF schematics?

**Comment by lbussy** [comment]
Eagle has a [free version](https://www.autodesk.com/products/eagle/free-download) which I use for all of my designs.  You can [download it](https://www.autodesk.com/products/eagle/free-download), install, and [print the schematic to PDF](https://www.digitaltrends.com/computing/print-pdf-windows/) (part of Windows) in about as much time as it took me to respond to this.

**Comment by ilium007** [comment]
I realise this but the schematic had no parts values, I just thought it might be easier to have a PDF included in the source files as is done on so many other projects I follow. I use KiCAD not Eagle so I don't have it installed locally.

**Comment by rob040** [comment]
I second the request.
Or better, add PNG of schematic and pcb's and add full BOM, especially when schematic don't come with component values.

The @[lbussy](https://github.com/lbussy) suggestion to download Eagle yourself is not as straightforward as it sounds. First, you have to register at Autodesk and part with your privacy to be able to use it. Next, there is issue #6, where it is reported that files can't be opened.

Therefore, the request to the team to make schematics, PCB prints and bom also available in general readable formats.

Update: instead of Eagle, the open source KiCad can be used to open Eagle projects. I have done so. I now understand why the schematics aren't publicized in any general readable format.

**Comment by rayshobby** [comment]
All current versions of board designs have PNG exports included in the folders.
